### ISSUE TITLE
Unable to build on Ubuntu 22.04.1

### ISSUE THREAD

**Issue by GothStar** [broadwaylamb/OpenCombine#240]
Building for debugging...
*/OpenCombine/Sources/COpenCombineHelpers/COpenCombineHelpers.cpp:10:10: fatal error: 'atomic' file not found
#include <atomic>
         ^~~~~~~~
1 error generated.
[1/10] Compiling COpenCombineHelpers COpenCombineHelpers.cpp

**Comment by Kyle-Ye** [comment]
I can compile it successfully on Ubuntu 22.04 on the current master branch (ff31c4337524760d8f342ee0659cd4c4b080a82f)

```
➜  OpenCombine git:(master) uname -a
Linux ubuntu-2204 6.1.23-orbstack-00113-g6614aaccb205-dirty #169 SMP Sat Apr  8 04:58:09 PDT 2023 aarch64 aarch64 aarch64 GNU/Linux
➜  OpenCombine git:(master) swift build
Building for debugging...
Build complete! (0.08s)
```

**Comment by Amzd** [comment]
On fedora I had to install clang to fix this error

```
sudo dnf install clang
```
